- name: Configure Satellite
  hosts:
    - satellite
  roles:
    - lab-organizations
  gather_facts: no
  pre_tasks:
    - name: Import configure variables
      include_vars:
        file: configure.yaml
    - name: Check if persistent variables file exists
      delegate_to: localhost
      stat:
        path: "{{ playbook_dir }}/persistent.yaml"
      register: persistent_exists
    - name: Import persistent variables
      when: persistent_exists.stat.exists
      include_vars:
        file: "{{ playbook_dir }}/persistent.yaml"
    - name: Import lab-configure variables
      include_vars:
        file: lab-configure.yaml
    - name: "Init accounts var"
      set_fact:
        accounts: []
        organizations: []
    - name: "Generate account list"
      with_sequence: start=1 end={{ lab_accounts }}
      set_fact:
        accounts: "{{ accounts + [ ('%02d' | format(item | int)) ] }}"
        organizations: "{{ organizations + [ ('Demo_%02d' | format(item | int)) ] }}"
    