---
- name: Install Satellite
  hosts:
    - satellite
  roles:
    - satellite-install
  pre_tasks:
  - name: Import configure variables
    include_vars:
      file: configure.yaml

- name: Configure Satellite
  hosts:
    - satellite
  roles:
    - configure-satellite
  pre_tasks:
  - name: Import configure variables
    include_vars:
      file: configure.yaml