---

- name: Install packages
  become: true
  package: 
    name: "{{ item }}"
    state: installed
  with_items: "{{ packages }}"

- name: Install packages for RHEL/CentOS 7
  become: true
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ packages7 }}"
  when: ansible_distribution_major_version == "7"

- name: Install packages for RHEL/CentOS 8
  become: true
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ packages8 }}"
  when: ansible_distribution_major_version == "8"

- name: Install jmespath
  local_action: true
  become: true
  ansible.builtin.pip:
    name: jmespath
