# The Organization that will be used during configuration
organization: "Default Organization"
# The Location that will be used during configuration
location: "Default Location"

# The admin username and password that will be used during configuration
admin_username: "admin"
admin_password: ""

# The manifest file to import
manifest_file: ""

# Additional Red Hat Repos to add
additional_redhat_repos: []

# Additional repos (none-RH)
additional_repos:
  - product: "EPEL"
    repo_name: "Everything 8"
    base_url: "https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/"
    gpg_key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL"
  - product: "EPEL"
    repo_name: "Modular 8"
    base_url: "https://dl.fedoraproject.org/pub/epel/8/Modular/x86_64/"
    gpg_key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL"

# Lifecycles to create
lifecycles:
  - prior: Library
    name: Dev
  - prior: Dev
    name: Prod

# Host groups to create
host_groups:
  - name: General
  - parent: General
    name: Domain
  - parent: General
    name: Non-Domain
  - parent: General/Domain
    name: "Department1"
  - parent: General/Domain/Department1
    name: "Department1-Dev"
    lifecycle: Dev
  - parent: General/Domain/Department1
    name: "Department1-Prod"
    lifecycle: Prod
  - parent: General/Non-Domain
    name: "Department2"
  - parent: General/Non-Domain/Department2
    name: "Department2-Dev"
    lifecycle: Dev
  - parent: General/Non-Domain/Department2
    name: "Department2-Prod"
    lifecycle: Prod

# Compute Resource to configure
compute_resources: []
#  - type: VMware
#    name: VMwareInstance
#    provider_params:
#      caching_enabled: false
#      url: vsphere.example.com
#      user: admin
#      password: secret
#      datacenter: ax01

subnets: []
# - name: NAME
#   description: DESCRIPTION
#   network: 10.0.0.0
#   cidr: 24
#   gateway: 10.0.0.1
#   dhcp_start: 10.0.0.11
#   dhcp_end: 10.0.0.254
#   dhcp_mode: DHCP
#   dhcp_server: satellite
#   tftp_server: satellite
#   dns_server: satellite
#   dns_servers: []
#   template_server: satellite
#   vlan_id: 0
#   mtu: 1500
#   domains:
#   - "domain1"
#   - "domain2"