---
- name: Create Hostgroup
  theforeman.foreman.hostgroup:
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    server_url: "https://localhost"
    validate_certs: false
    organization: "{{ organization }}"
    name: "{{ part }}"
    architecture: "x86_64"
    state: present
    parent: "{{ parent | default(omit) }}"
    lifecycle_environment: "{{ lifecycle if ( ( ( part | split('-') )[-1] ) == lifecycle ) else 'Library' if part == 'General' else omit }}"
    environment: "{{ lifecycles | json_query('[?name == `' ~ lifecycle ~ '`].puppet') | first if ( ( ( part | split('-') )[-1] ) == lifecycle ) else default_environment if part == 'General' else omit }}"
    content_view: "{{ default_contentview if part == 'General' }}"
    content_source: "{{ groups['satellite'][0] if part == 'General' }}"
    puppet_proxy: "{{ groups['satellite'][0] if part == 'General' }}"
    puppet_ca_proxy: "{{ groups['satellite'][0] if part == 'General' }}"
    activation_keys: "rhel-{{ lifecycle | lower if ( ( ( part | split('-') )[-1] ) == lifecycle ) else omit }}"
  tags:
    - satellite-configure
    - satellite-configure-hostgroups

- name: Append parentpart
  when: parent != ""
  ansible.builtin.set_fact:
    parent: "{{ parent }}/{{ part }}"
  tags:
    - satellite-configure
    - satellite-configure-hostgroups

- name: Set parent
  when: parent == ""
  ansible.builtin.set_fact:
    parent: "{{ part }}"
  tags:
    - satellite-configure
    - satellite-configure-hostgroups
