---
- name: Query for site health
  ansible.builtin.uri:
    url: "http://localhost/"
    status_code: "403"
  ignore_errors: true
  register: site_health

- name: Ensure the service is running
  when: site_health.failed
  ansible.builtin.service:
    name: httpd
    state: started

- name: Query for site health
  when: site_health.failed
  ansible.builtin.uri:
    url: "http://localhost/"
    status_code: "403"
