---
 
- name: Check if bugfix file exists
  when: bug in bugfixes
  delegate_to: localhost
  stat:
    path: "{{ role_path }}/tasks/bugfixes/{{ bug }}.yaml"
  register: bug_exists
  tags:
    - always

- name: Run bugfix
  when: bug in bugfixes and bug_exists.stat.exists
  include_tasks:
    file: "{{ role_path }}/tasks/bugfixes/{{ bug }}.yaml"
  tags:
    - always