---

- name: Check if persistent variables file exists
  delegate_to: localhost
  stat:
    path: "{{ playbook_dir }}/persistent.yaml"
  register: persistent_exists
  tags:
    - always

- name: Import persistent variables
  when: persistent_exists.stat.exists
  include_vars:
    file: "{{ playbook_dir }}/persistent.yaml"
  tags:
    - always

- name: Check Prerequisites
  include_tasks: "{{ role_path }}/tasks/pre-reqs.yaml"
  tags:
    - satellite-install
    - satellite-install-prereqs

- name: Enable Repositories
  include_tasks: "{{ role_path }}/tasks/repos.yaml"
  tags:
    - satellite-install
    - satellite-install-repos

- name: Install Dependencies
  include_tasks: "{{ role_path }}/tasks/dependencies.yaml"
  tags:
    - satellite-install
    - satellite-install-dependencies


- name: Update all packages
  become: true
  package:
    name: '*'
    state: latest
  tags:
    - satellite-install
    - satellite-install-updateall

- name: Check if a restart is required
  ansible.builtin.command:
    cmd: needs-restarting -r
  register: needsrestart
  ignore_errors: true
  tags:
    - satellite-install
    - satellite-install-updateall
    - satellite-install-updateall-reboot

- name: Reboot server
  when: needsrestart == 1
  ansible.builtin.reboot:
  tags:
    - satellite-install
    - satellite-install-updateall
    - satellite-install-updateall-reboot

- name: Install Satellite
  include_tasks: "{{ role_path }}/tasks/install.yaml"
  tags:
    - satellite-install
    - satellite-install-installer

- name: Configure Firewalld
  include_tasks: "{{ role_path }}/tasks/firewall.yaml"
  tags:
    - satellite-install
    - satellite-install-firewall
