---

- name: Create host groups
  loop: "{{ lookup('ansible.utils.to_paths', host_groups) | list }}"
  tags:
    - hostgroups
  include_tasks: "{{ role_path }}/tasks/hostgroups/department_loop.yml"
  loop_control:
    loop_var: hostgroup