---

- name: Install R10k gem
  community.general.gem:
    name: r10k
    user_install: false

- name: Clone general modules
  ansible.builtin.git:
    repo: 'https://github.com/JasonN3/puppet_modules.git'
    dest: /etc/puppetlabs/code/modules/
    version: main

- name: Configure r10k
  when: puppet_sources is defined and puppet_sources != {}
  block:
  - name: Write R10k configuration file
    ansible.builtin.template:
      src: "{{ role_path }}/templates/r10k.conf.j2"
      dest: /etc/puppetlabs/r10k.conf
      owner: puppet
      group: puppet
      mode: '0644'

  - name: Add pre-run command to puppet server
    community.general.ini_file:
      path: /etc/puppetlabs/puppet/puppet.conf
      section: agent
      option: prerun_command
      value: 'r10k deploy environment -p -c /etc/puppetlabs/r10k.conf'

  - name: Initial sync
    ansible.builtin.command:
      cmd: 'r10k deploy environment -p -c /etc/puppetlabs/r10k.conf'

- name: Sync Puppet modules
  theforeman.foreman.puppetclasses_import:
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    server_url: "https://localhost"
    validate_certs: false
    smart_proxy: "{{ ansible_fqdn }}"

