---

- name: Get all enabled products
  theforeman.foreman.resource_info:
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    server_url: "https://localhost"
    validate_certs: false
    resource: products
    organization: "{{ organization }}"
  register: products
  tags:
    - syncplan

- name: Create daily sync plan and assign to all products
  theforeman.foreman.sync_plan:
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    server_url: "https://localhost"
    validate_certs: false
    name: "Daily Sync"
    organization: "{{ organization }}"
    interval: "daily"
    enabled: true
    sync_date: "2022-01-01 00:00:00 UTC"
    products: "{{ products | json_query('resources[?repository_count > `0`].name') }}"
    state: present
  tags:
    - syncplan
